// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cognito_identity_pool_id': 'us-east-1:1406fd0e-cebe-40d6-9967-e570386a6587',
    'aws_cognito_region': 'us-east-1',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'rnexpoauthproject-hosting-mobilehub-1997181428',
    'aws_content_delivery_bucket_region': 'us-east-1',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'ditu1vzvaitm.cloudfront.net',
    'aws_mobile_analytics_app_id': 'c582cd386ab24a3ebfc0c8faa3320113',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': 'b3131e59-18b2-11e8-ac43-4901fe0615a8',
    'aws_project_name': 'RNExpoAuthProject',
    'aws_project_region': 'us-east-1',
    'aws_resource_name_prefix': 'rnexpoauthproject-mobilehub-1997181428',
    'aws_sign_in_enabled': 'enable',
    'aws_user_pools': 'enable',
    'aws_user_pools_id': 'us-east-1_yQD5JOPBI',
    'aws_user_pools_mfa_type': 'ON',
    'aws_user_pools_web_client_id': '3vtel445aiutov3ifu299gmku0',
}

export default awsmobile;
